"""Inject any skin directory into the official market facade and render previews.

Generalised from the Lucy-specific script: takes the skin directory and id, copies
the skin into <facade>/assets/skins/<id>/, appends its manifest entry to
`window.SKIN_MANIFEST` and its stylesheet texts to `window.SKIN_STYLES` - which is
exactly what the market build does for every published skin.

Usage:
  python inject_skin_into_facade.py <skin-dir> <id> <facade-dir>
"""
import json
import re
import shutil
import sys
from pathlib import Path

skin_dir = Path(sys.argv[1])
skin_id = sys.argv[2]
facade = Path(sys.argv[3])

manifest_path = facade / 'manifest.js'
styles_path = facade / 'styles.js'


def load_js(path: Path, global_name: str):
    text = path.read_text(encoding='utf-8')
    text = re.sub(r'^/\*.*?\*/\s*', '', text, count=1, flags=re.S)
    prefix = f'window.{global_name} = '
    assert text.startswith(prefix), text[:80]
    payload = text[len(prefix):].strip().rstrip(';')
    return json.loads(payload)


def dump_js(path: Path, global_name: str, data) -> None:
    body = json.dumps(data, ensure_ascii=False, indent=2)
    path.write_text(f'/* Generated by scripts/market-build — do not edit by hand. */window.{global_name} = {body}',
                    encoding='utf-8')


manifest = load_js(manifest_path, 'SKIN_MANIFEST')
styles = load_js(styles_path, 'SKIN_STYLES')
skin = json.loads((skin_dir / 'skin.json').read_text(encoding='utf-8'))

styles[skin_id] = {
    'stylesheet': (skin_dir / skin['contributes']['stylesheet']).read_text(encoding='utf-8'),
}
if 'patches' in skin['contributes']:
    styles[skin_id]['patches'] = (skin_dir / skin['contributes']['patches']).read_text(encoding='utf-8')

prefix = f'assets/skins/{skin_id}/'
entry = {
    'id': skin_id,
    'name': skin['name'],
    'nameEn': skin['nameEn'],
    'author': skin['author'],
    'tagline': skin['tagline'],
    'description': skin['description'],
    'accent': skin['accent'],
    'preview': {'light': prefix + 'preview/light.jpg', 'dark': prefix + 'preview/dark.jpg'},
    'contributes': {
        'stylesheet': skin['contributes']['stylesheet'],
    },
}
if 'patches' in skin['contributes']:
    entry['contributes']['patches'] = skin['contributes']['patches']
if 'backgroundMedia' in skin['contributes']:
    entry['contributes']['backgroundMedia'] = {
        theme: {'type': v['type'], 'src': prefix + v['src'], 'scrim': v['scrim']}
        for theme, v in skin['contributes']['backgroundMedia'].items()
    }

manifest['skins'] = [s for s in manifest['skins'] if s.get('id') != skin_id] + [entry]
dump_js(manifest_path, 'SKIN_MANIFEST', manifest)
dump_js(styles_path, 'SKIN_STYLES', styles)

dest = facade / 'assets' / 'skins' / skin_id
if dest.exists():
    shutil.rmtree(dest)
shutil.copytree(skin_dir, dest)
(dest / 'preview').mkdir(exist_ok=True)

print(f'injected {skin_id}: {len(manifest["skins"])} skins in the facade, style entries {len(styles)}')
